---
- hosts: localhost
  gather_facts: yes
  become: yes
  become_user: ec2-user
  tasks:
  - name: Download Long Term Jenkins release
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
  - name: Import jenkins key from url
    ansible.builtin.rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
  - name: Update yum repository 
    command: yum update -y
    register: yum_out
  - debug: msg="{{ yum_out }}"
  - name: Install java 
    command: yum install -y java
    register: java_out
  - debug: msg="{{ java_out }}"
  - name: Install jenkins
    command: yum install -y jenkins
    register: jenkins_out
  - debug: msg="{{ jenkins_out }}"
  - name: Jenkins service starting
    command: systemctl start jenkins.service
    register: start_service_out
  - debug: msg="{{ start_service_out }}"
  - name: Jenkins service status checking
    command: systemctl status jenkins.service
    register: service_out
  - debug: msg="{{ service_out }}"
